apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backup.serviceAccountName }}
  namespace: {{ .Values.namespace }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cephfs-backup-job
subjects:
  - kind: ServiceAccount
    name: {{ .Values.backup.serviceAccountName }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  # Use cephfs-csi-driver-ceph-csi-cephfs-provisioner to patch pvs when annotating them
  name: cephfs-csi-driver-ceph-csi-cephfs-provisioner
  apiGroup: rbac.authorization.k8s.io

---
# It needs to read the secrets of the namespace of the driver
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-secrets
subjects:
  - kind: ServiceAccount
    name: {{ .Values.backup.serviceAccountName }}
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader
